#!/bin/bash

# Folder containning all the patients, images  and fields
cd /home/leonardo/Documents/Doutorado/q-Evaluation-Rig-Reg-Projeto-Greg
current=`echo $PWD`

# Folder containning the executable
exeDir=/home/leonardo/Documents/Doutorado/Image-Registration/DVFcomparison/debug

# reference fields for comparison
dispFieldRefFolder=/a/lfm23/Doutorado/ACRIN/DispFieldsSpecialists      

# folder containing the masks used in the comparison
maskfFolder=/home/leonardo/Documents/Doutorado/q-Evaluation-Rig-Reg-Projeto-Greg/CT-Brain-Mask     

# Deciding which results folder to process 
res='NormalizedResults'
#res='NonNormalizedResults'

#`ls -A1`
refFieldsi=0
entropyType='Tsallis'
entropyType='TsallisNorm'

for folder in `ls -A1 *0*`; do
	
	echo "Patient /$folder ---------------------------------------------------------."
    
	# Listing and entering only patient's folder and creat a CSV for 
	# storing q-value vs dispField agreement 
	cd $current/$folder
	csv=$current/$folder/DVFComparison-${entropyType}-${folder}.csv
	#echo "#Patient $folder" >> $csv
	echo "qValue,WholeFieldAgreement,MaskedFieldAgreement" >> $csv 
	
	# pick fieldRef
	fieldRefName=DisplacementField$folder.nrrd
	if test -f "$dispFieldRefFolder/$fieldRefName"; then
		fieldRef=$dispFieldRefFolder/$fieldRefName
		refFieldsi=$((refFieldsi+1))
	else
		echo "Reference Field $fieldRefName does not exist!"
	fi

	# pick maskRef
	maskRefName=mask$folder{Resample}.nrrd
	if test -f "$maskFolder/$maskName"; then
		mask=$maskFolder/$maskName
	else
		echo "Mask $maskName does not exist!"
	fi


	i=0 # counter for found pair of images
	for field in `ls -A1 *DisplacementField*`; do
	    
		fieldName=${field%'.nrrd'}
		qValue=${fieldName##*'DisplacementField_q='}	
	
		fieldTested=$current/$folder/$res/$field 
		# Catching plastimatch output
		comparisonWholeImage=`$exDir/DVFcomparison $fieldRef $fieldTested $maskRefile`
		comparisonMaskedImage=`$exDir/DVFcomparison $fieldRef $fieldTested`
	
		# Printing into file
		echo "$qValue,$comparisonWholeImage,$comparisonMaskedImage" >> $csv
		
		echo 'Patient = '$folder --'qValue = ' $qValue --'Whole Aver. Diff. = '$comparisonWholeImage --'Masked = '$comparisonMaskedImage  
		
		i=$((i+1))

		#fildAgrement=$pmDir/plastimatch compare  ${dispFieldRef}$folder vf-trans-1.mha | grep Ave | sed -e 's/[^-0-9]*//'
	done
	echo $i
done
echo $refFieldsi